version: "3.9"

services:
    flex:
        container_name: flex
        build: ./frontend/
        depends_on:
            - flex_api
        networks: 
            - external
            - internal

    flex_api:
        container_name: flex_api
        build: ./backend/
        environment:
            PORT: 8080
        env_file: .env.prod
        depends_on:
            - mongo
        networks: 
            - external
            - internal

    mongo:
        container_name: flex_db
        image: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: pass
        networks: 
            - internal

networks: 
    external:
        name: secure_network
    internal:
        internal: true

